import Head from 'next/head'
import { useAuth0 } from "@auth0/auth0-react";

export default function Home(props: any) {
  const { isAuthenticated } = useAuth0();
  const { loginWithRedirect } = useAuth0();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isAuthenticated ? <p>ログイン中です</p> : <p>ログアウトしています</p>}
      {props.laboratories.map((laboratory: any) => {
        return (
          <div key={laboratory.id}>
            <h1>{laboratory.name}</h1>
            <p>{laboratory.teacher}</p>
          </div>
        )
      })}
    </>
  )
}

export const getStaticProps = async () => {
  // URLはlocalhostではなくapiとなる
  const response = await fetch("http://localhost:3000/laboratories", {method: "GET"});
  const json = await response.json();
  console.log(json)

  return {
    props: {
      laboratories: json
    },
  };
}
