import Head from 'next/head'
import { useAuth0 } from "@auth0/auth0-react";
import { useEffect, useState } from 'react';
import { useApiAgent } from '@/lib/api_agent';
import { User } from '@/resources/types';
import { useRouter } from 'next/router';

export default function Survey() {
  const { isLoading, isAuthenticated } = useAuth0();
  const apiAgent = useApiAgent();
  const [user, setUser] = useState<User | null>(null)
  const [survey, setSurveyName] = useState<any>([
  const router = useRouter()

  const fetchUser = async () => {
    apiAgent({
      url: `/api/users`,
      method: 'GET',
    })
      .then((response) => response.json())
      .then((json) => {
        setUser(json.user)
      })
  }

  const fetchSurvey = async () => {
    apiAgent({
      url: `/api/survey`,
      method: 'GET',
    })
      .then((response) => response.json())
      .then((json) => {
        console.log(json)
      })
  }

  useEffect(() => {
    fetchUser()

    if (!user) {
      router.push('/')
    }
    fetchSurvey()
  }, [])

  return (
    <>
      <Head>
        <title>KUlabMatch | survey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && user.affiliation}
    </>
  )
}
